spring.application.name=loan-application

# Server port
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# Database Configuration (Uses Railway PostgreSQL if DATABASE_URL is present, otherwise H2 locally)
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:loandb}
spring.datasource.username=${POSTGRES_USER:sa}
spring.datasource.password=${POSTGRES_PASSWORD:password}

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger UI / OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
